comp/urls.py
from django.conf.urls import include, url
from . import views



urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^thanks/$',views.thanks,name='thanks'),
    url(r'^heatmap/$',views.hmap,name='hmap'),
]

envimaps2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# 

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^home/', include('comp.urls',namespace='home')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

comp/models.py
from django.db import models
import os





class Complaint(models.Model):

    title = models.CharField(max_length=200)
    desc = models.TextField(max_length=400)
    location = models.CharField(max_length = 100)

    
    lat = models.FloatField(default="0")
    lon = models.FloatField(default="0")

    pic = models.ImageField(upload_to='img')

    date_published = models.DateTimeField(auto_now_add = True)
    date_modified = models.DateTimeField(auto_now = True)

    def __unicode__(self):
        return self.title

comp/forms.py
from django import forms




class AddForm(forms.Form):



	title = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class':'form-control'}))

	location = forms.CharField(max_length = 100, widget=forms.TextInput(attrs={'class':'form-control'}))
	desc = forms.CharField(label="Description", max_length=400, widget=forms.TextInput(attrs={'class':'form-control'}))
	pic = forms.ImageField(label="Upload Image")

	# name.widget.attrs.update({'class': 'special'})
	pic.widget.attrs.update({'class':'form-control'})
	# myfield = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}))

	# title = forms.CharField(max_length=200)
	# desc = forms.CharField(max_length=400)
	# location = forms.CharField(max_length = 100)
	# pic = forms.ImageField()


	# date_published = forms.DateTimeField(auto_now_add = True)
	# date_modified = forms.DateTimeField(auto_now = True)

comp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
import requests
# Create your views here
from .models import Complaint
from .forms import AddForm


def index(request):
    if request.method == 'POST':
        # create a form instance and popuslate it with data from the request:
        form = AddForm(request.POST, request.FILES)
        # check whether it's valid:
        if form.is_valid():
            title = request.POST.get('title', '')
            desc = request.POST.get('desc', '')
            location = request.POST.get('location', '')
            r = requests.get(
                "https://maps.googleapis.com/maps/api/geocode/json?address=" + location + "&key=AIzaSyCIXeZdC33t1bfnjdPKGmoVg5ebtT4ddNY")
            json = r.json()
            results = json['results']
            latLng = {'lat': 25.2234975, 'lng': 73.7477857}
            if(len(results) > 0):
                latLng = results[0]['geometry']['location']
            # {'lat': 25.2234975, 'lng': 73.7477857}
            pic = request.FILES.get('pic', '')
            comp_obj = Complaint(lat=latLng['lat'], lon=latLng['lng'], title=title, desc=desc, location=location,
                                 pic=pic)
            comp_obj.save()
            return HttpResponseRedirect(reverse('home:thanks'))
            # return render(request, 'ES/index2.html', context)

        # if a GET (or any other method) we'll create a blank form
    else:
        form = AddForm()
        comp_list = Complaint.objects.all().order_by('-date_published')
        count = Complaint.objects.count()

        k = 0
        list_one = []
        list_rest = []
        for i in comp_list:
            if (k == 0):
                list_one.append(i)
            else:
                list_rest.append(i)
            k = k + 1

        # count_3 = count//3
        # if(count%3!=0):
        #   count_3 +=1

        # k=0
        # comp_sub_list=[]
        # comp_sub_list_one=[]

        # loc_list=[]

        # # print(count_3)
        # for i in comp_list:
        #   loc_list.append(str(i.location))

        # for i in range(0,count_3):
        #   comp_sub=[]

        #   if(i==count_3-1 and count%3!=0):
        #     r = range(0,count%3)

        #   else:
        #     r = range(0,3)
        #   # print(r)
        #   for j in r:
        #     comp_sub.append(comp_list[k])
        #     k=k+1
        #     # print(k)

        #   if(i==0):
        #     comp_sub_list_one = comp_sub
        #   else:
        #     comp_sub_list.append(comp_sub)

        # count_range = range(1,count_3)
        count_range = range(1, count)

        # context = {'comp':comp_list, 'sub_list':comp_sub_list, 'list_one':comp_sub_list_one,'r':count_range, 'form':form, 'loc':loc_list}
        context = {'comp': comp_list, 'r': count_range, 'one': list_one, 'rest': list_rest, 'form': form}

        # count_3 = count//3
        # if(count%3!=0):
        #   count_3 +=1

        # k=0
        # comp_sub_list=[]
        # comp_sub_list_one=[]

        # loc_list=[]
        # lat_list=[]
        # lon_list=[]
        # # print(count_3)
        # for i in comp_list:
        #   loc_list.append(str(i.location))
        #   lat_list.append(i.lat)
        #   lon_list.append(i.lon)

        # for i in range(0,count_3):
        #   comp_sub=[]

        #   if(i==count_3-1 and count%3!=0):
        #     r = range(0,count%3)

        #   else:
        #     r = range(0,3)
        #   # print(r)
        #   for j in r:
        #     comp_sub.append(comp_list[k])
        #     k=k+1
        #     # print(k)

        #   if(i==0):
        #     comp_sub_list_one = comp_sub
        #   else:
        #     comp_sub_list.append(comp_sub)

        # count_range = range(1,count_3)
        # context = {'comp':comp_list, 'sub_list':comp_sub_list, 'list_one':comp_sub_list_one,'r':count_range, 'form':form, 'loc':loc_list, 'lat':lat_list, 'lon':lon_list}

    return render(request, 'ES/index.html', context)


# def add_comp(request):

#     if request.method == 'POST':
#         # create a form instance and popuslate it with data from the request:
#         form = AddForm(request.POST, request.FILES)
#         # check whether it's valid:
#         if form.is_valid():

#            title = request.POST.get('title','')
#            desc = request.POST.get('desc','')
#            location = request.POST.get('location','')
#            pic = request.FILES.get('pic','')
#            comp_obj = Complaint(title = title,desc = desc, location=location, pic = pic)
#            comp_obj.save()
#            return HttpResponseRedirect(reverse('home:index'))


#     # if a GET (or any other method) we'll create a blank form
#     else:
#         form = AddForm()

#     return render(request, 'ES/index.html', {'form': form})


def thanks(request):
    return render(request, 'ES/thanks.html')


def hmap(request):
    comp_list = Complaint.objects.all()
    # [ [l,l], [l,l] ]
    latLng = []
    for i in comp_list:
        sub_list=[]
        sub_list.append(i.lat)
        sub_list.append(i.lon)
        latLng.append(sub_list)
    context = {'latLng':latLng}
    return render(request, 'ES/heatmap.html', context)

comp/templates/ES/base.html
<!DOCTYPE html>
<html>

<head>

    {% load static from staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Envi</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700">
    <link rel="stylesheet" href="{% static 'css/Contact-Form-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'css/Features-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'css/Footer-Dark.css' %}">
    <link rel="stylesheet" href="{% static 'css/Header-Blue.css' %}">
    <link rel="stylesheet" href="{% static 'css/Highlight-Phone.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
    <link rel="stylesheet" href="{% static 'css/Lightbox-Gallery.css' %}">
    <link rel="stylesheet" href="{% static 'css/Map-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'css/Navigation-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'css/Navigation-with-Button.css' %}">
    <link rel="stylesheet" href="{% static 'css/Navigation-with-Search.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block head %}{% endblock %}

</head>

<body>
    <div></div>

    <div>
        <div class="header-blue">
            <nav class="navbar navbar-dark navbar-expand-md navigation-clean-search">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'home:index' %}">EnviMaps</a><button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse"
                        id="navcol-1">
                        <ul class="nav navbar-nav">
                            {% block links %}
                            <li class="nav-item" role="presentation"><a class="nav-link active" href="#report">REPORT NOW!</a></li>
                            <!--<li class="dropdown"><a class="dropdown-toggle nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Menu </a>-->
                                <!--<div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="#comp">Complaints</a><a class="dropdown-item" role="presentation" href="#map">Heatmap</a><a class="dropdown-item" role="presentation" href="#about">About Us</a></div>-->
                            <!--</li>-->

                            <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'home:hmap' %}">HEAT MAP</a></li>

                            <li class="nav-item" role="presentation"><a class="nav-link" href="#comp">COMPLAINTS</a></li>
                            {% endblock %}
                        </ul>
                        <form class="form-inline mr-auto" target="_self">
                            <div class="form-group"><label for="search-field"><i class="fa fa-search"></i></label><input class="form-control search-field" type="search" name="search" id="search-field"></div>
                        </form><span class="navbar-text"> <a href="#" class="login">Log In</a></span><a class="btn btn-light action-button" role="button" href="#">Sign Up</a>
                    </div>
                </div>
            </nav>
            {% block cm %}
            {% endblock %}
        </div>
    </div>
{% block body %} {% endblock %}
    <div class="footer-dark">


        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li><a href="#">Web design</a></li>
                            <li><a href="#">Development</a></li>
                            <li><a href="#">Hosting</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Elliot Stark</h3>
                        <p>Help people you care about & those around you be safe by reporting an evrionmental issue right now!</p>
                    </div>
                    <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">Elliot Stark © 2018</p>
            </div>
        </footer>
    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox.min.js"></script>
</body>

</html>

comp/templates/ES/heatmap.html
{% extends 'ES/base.html' %}
{% load static from staticfiles %}
{% block head %}
    <style>
        /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */

        #map {
            height: 100%;
        }

        /* Optional: Makes the sample page fill the window. */

        html,
        body {
            height: 100%;
            margin: 0;
            padding: 0;
        }
    </style>
{% endblock %}
{% block links %}
                            <li class="nav-item" role="presentation"><a class="nav-link" href="#report">REPORT NOW!</a></li>
                            <!--<li class="dropdown"><a class="dropdown-toggle nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Menu </a>-->
                                <!--<div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="#comp">Complaints</a><a class="dropdown-item" role="presentation" href="#map">Heatmap</a><a class="dropdown-item" role="presentation" href="#about">About Us</a></div>-->
                            <!--</li>-->

                            <li class="nav-item" role="presentation"><a class="nav-link active" href="{% url 'home:hmap' %}">HEAT MAP</a></li>

                            <li class="nav-item" role="presentation"><a class="nav-link" href="#comp">COMPLAINTS</a></li>
                            {% endblock %}
{% block body %}
    <script src="{% static 'js/heatmap.js' %}"></script>
    <body onload="updateDataPoints({{ latLng }})">
    <div id="map"></div>

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAlL0EinRTWJbAdRfUbWNowPu4Tk03ECwI&libraries=visualization&callback=initMap">
    </script>
    </body>
{% endblock %}

comp/templates/ES/index.html
{% extends 'ES/base.html' %}

    {% load staticfiles %}


    {% block cm %}
        <div class="container hero">
            <div class="row">
                <div class="col-12 col-lg-6 col-xl-5 offset-xl-1">
                    <h1>Welcome to EnviMaps</h1>

                    <p>Help people you care about & those around you be safe by reporting an evrionmental issue right
                        now!</p><a href="#report">
                    <button class="btn btn-light btn-lg action-button" type="button">REPORT NOW</button>
                </a>
                </div>

                <div
                        class="col-md-5 col-lg-5 offset-lg-1 offset-xl-0 d-none d-lg-block phone-holder">
                    <div class="iphone-mockup"><img src="{% static 'img/cm.jpg' %}" class="device">
                    </div>
                    <div class="screen"></div>
                </div>
            </div>
        </div>
    {% endblock %}
    {#        </div>#}
{% block body %}
    <div class="features-clean" style="background-color:rgb(241,247,252);height:100%;">
        <div class="container" id="comp">
            <div>
                <h2 class="text-center">Recent Complaints</h2>
            </div>
            <div class="row">
                <div class="col-xl-10 offset-xl-1">
                    <div class="carousel slide" data-ride="carousel" id="carousel-1">
                        <div class="carousel-inner" role="listbox">

                            {% for i in one %}

                                <div class="carousel-item active"><img class="w-100 d-block" src="{{ i.pic.url }}"
                                                                       alt="Slide Image" height="400px" width="600px">
                                    <div class="carousel-caption carousel-caption-back">
                                        <h3>{{ i.title }}</h3>
                                        <p>{{ i.desc }}</p>
                                        <p>{{ i.location }}</p>
                                    </div>
                                </div>
                            {% endfor %}
                            {% for i in rest %}

                                <div class="carousel-item"><img class="w-100 d-block" src="{{ i.pic.url }}"
                                                                alt="Slide Image" height="400px" width="600px">
                                    <div class="carousel-caption carousel-caption-back">
                                        <h3>{{ i.title }}</h3>
                                        <p>{{ i.desc }}</p>
                                        <p>{{ i.location }}</p>
                                    </div>
                                </div>
                            {% endfor %}


                        </div>
                        <div><a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev"><span
                                class="carousel-control-prev-icon"></span><span class="sr-only">Previous</span></a><a
                                class="carousel-control-next" href="#carousel-1" role="button"
                                data-slide="next"><span class="carousel-control-next-icon"></span><span class="sr-only">Next</span></a>
                        </div>
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-1" data-slide-to="0" class="active"></li>

                            {% for i in r %}
                                <li data-target="#carousel-1" data-slide-to="{{ i }}"></li>
                            {% endfor %}

                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="features-clean" style="background-color:rgb(241,247,252);" id="report">
        <div class="container">
            <div>
                <h2 class="text-center">Report</h2>
            </div>
            <div class="row justify-content-between">
                <div class="col-12 col-sm-12 col-md-10 col-lg-8 col-xl-6 offset-0 offset-sm-0 offset-md-1 offset-lg-2 offset-xl-3">
                    <div>


                        <form action="{% url 'home:index' %}" method="post" enctype="multipart/form-data">

                            {% csrf_token %}
                            {{ form }}
                            <br>
                            <button class="btn btn-primary btn-lg" type="submit">Report</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

comp/templates/ES/thanks.html
{% extends 'ES/base.html' %}

{% block body %}

THANKS YOUR RESPONSE HAS BEEN RECORDED
<p>
<a href ="{% url 'home:index' %}" > GO BACK </a>
</p>

{% endblock %}